version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS:        "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT:    zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
